- src/main.rs
> scan arguments that contain whitespace by splitting them first

- CHANGELOG.md
- Cargo.lock
- src/sysroot.rs
> build sysroot from current directory

- CHANGELOG.md
- Cargo.lock
- src/sysroot.rs
> rebuild the sysroot when rust-src changes

- CHANGELOG.md
- Cargo.lock
- src/sysroot.rs
- tests/smoke.rs
this has been the case for Cargo for a while now.
> print all status messages to stderr

- CHANGELOG.md
- src/sysroot.rs
> stop using hardlinks

- CHANGELOG.md
- src/main.rs
like clean and update
closes #49
> don't trigger sysroot rebuilds on some commands

- .rustfmt.toml
- .travis.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- appveyor.yml
- build.rs
- ci/docker/i686-unknown-linux-gnu/Dockerfile
- ci/docker/i686-unknown-linux-musl/Dockerfile
- ci/docker/x86_64-unknown-linux-musl/Dockerfile
- ci/install.ps1
- ci/run-docker.sh
- ci/run.sh
- src/cargo.rs
- src/errors.rs
- src/flock.rs
- src/fs.rs
- src/io.rs
- src/main.rs
- src/parse.rs
- src/rustc.rs
- src/sysroot.rs
- src/toml.rs
- src/xargo.rs
- tests/smoke.rs
Xargo now depends on the rust-src component, which can be installed via
rustup
> v2: drop a bunch of dependencies

- .travis.yml
- ci/docker/i686-unknown-linux-gnu/Dockerfile
- ci/docker/i686-unknown-linux-musl/Dockerfile
- ci/docker/x86_64-unknown-linux-gnu/Dockerfile
- ci/docker/x86_64-unknown-linux-musl/Dockerfile
- ci/run-docker.sh
- ci/run.sh
> unbreak the cache

- .travis.yml
- appveyor.yml
- ci/install.ps1
- ci/package.sh
- ci/run-docker.sh
- ci/run.sh
> backport trust's faster-deploy branch

- src/main.rs
print them using Display not Debug
> nicer errors messages

- CHANGELOG.md
- src/sysroot.rs
- tests/smoke.rs
> don't rebuild the sysroot if profile.*.lto changed in Cargo.toml

- CHANGELOG.md
- src/sysroot.rs
- tests/smoke.rs
> don't recompile the sysroot if the linker flags have changed

- src/rustc.rs
- tests/smoke.rs
> Fix search for rustup rust-src component

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
- src/rustc.rs
- src/sysroot.rs
- src/xargo.rs
- tests/smoke.rs
> build a sysroot when compiling natively

- CHANGELOG.md
- src/sysroot.rs
> allow relative paths in dependencies.{}.path

- README.md
Not completely sure on the wording but I thought this was worth noting
> Add a note about a cargo issue with plugins (#125)

- src/util.rs
> Fixed an issue where xargo could not copy files recursively on windows

- src/sysroot.rs
Fixes building libtest on current nightly.
Fixes #140
> Pass "-Z force-unstable-if-unmarked" to Rustc

- build.rs
- src/cargo.rs
- src/cli.rs
- src/extensions.rs
- src/flock.rs
- src/main.rs
- src/rustc.rs
- src/sysroot.rs
- src/util.rs
- src/xargo.rs
- tests/smoke.rs
see #44 and rust-lang/rust#24666
> reject `--target foo.json`; suggest `--target foo`

- .travis.yml
- src/cargo.rs
- src/cli.rs
- src/extensions.rs
- src/flock.rs
- src/main.rs
- src/rustc.rs
- src/sysroot.rs
- src/util.rs
- src/xargo.rs
- tests/smoke.rs
let's see if clearing the cache fixes the problem reported in rust-lang/cargo#4699
> use recent nightly for macOS

- src/sysroot.rs
When linking `std.dll` and the other output executables for `windows-gnu` targets, the linker will complain that various object files are missing. They seem to be necessary only for `windows-gnu`, see also [this function](https://github.com/rust-lang/rust/blob/19e63bd50eb756e35416d7a8f01e2d63f419b373/src/bootstrap/compile.rs#L272).
Tested on Windows 7 64 bit.
> Fix linking for pc-windows-gnu targets

- README.md
Fixes #181 
@japaric Is this all correct?
> Recommend always using --target option

- src/sysroot.rs
to let rustc find custom target specification files located in the current directory
closes #186
> set RUST_TARGET_PATH when compiling the sysroot

- src/sysroot.rs
- src/xargo.rs
- tests/smoke.rs
Depends on #234
Partial solution for #230
**TODO**
> Allow specifying [patch] in Xargo.toml 

- src/sysroot.rs
- src/xargo.rs
- tests/smoke.rs
> Make sure to use Xargo.toml directory when resolving path

- src/sysroot.rs
> Set Cargo.lock writable

- ci/script.sh
@jethrogb This seems like a useful thing to do on CI?
> CI: make sure the lockfile is up-to-date

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> version 0.3.18

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
I also used the opportunity for a `cargo update`
> version bump for 0.3.19 release

- ci/install.sh
> cross no longer provides linux-gnu binaries, but linux-musl

- CHANGELOG.md
> document final release date

- .travis.yml
- Cargo.lock
- Cargo.toml
- tests/smoke.rs
These are the ones that do not require changes to the code.
> update some dependencies

- src/rustc.rs
- src/sysroot.rs
This fixes xargo to work with https://github.com/rust-lang/rust/pull/73265.
We should wait until the next nightly is released so that CI tests a nightly with the new directories.
> fix for changed rustc directory layout

- src/cargo.rs
- src/cli.rs
- src/lib.rs
- src/rustc.rs
- tests/smoke.rs
Fix for https://github.com/japaric/xargo/issues/215
> fix: use manifest path for xargo.toml if provided

- .github/workflows/ci.yml
- src/sysroot.rs
@Selyatin  can you test if this fixes https://github.com/japaric/xargo/issues/313?
> windows extra files: support both old and new locations

- CHANGELOG.md
Let's release https://github.com/japaric/xargo/pull/331.
> release v0.3.25

- .github/workflows/ci.yml
- src/cargo.rs
- src/sysroot.rs
- src/xargo.rs
- tests/smoke.rs
Fixes https://github.com/japaric/xargo/issues/206
> Fix handling spaces in the sysroot path

- README.md
> explain where XARGO_RUST_SRC must point to
