- ci/script.sh
the former limits the compilation phase to one rustc process, the later
executes the tests in a single thread. We actually want the later.
> -j1 -> RUST_TEST_THEADS=1

- CHANGELOG.md
- src/main.rs
- src/sysroot.rs
> forward the `--verbose` flag to the `cargo` call that builds the sysroot

- README.md
Add a reference to the Debian CMake OpenSSL detection bug which breaks libssh2 builds. This reference can be removed once the package is moved from proposed-updates to updates.
Hopefully there is enough information in the description to at least point people in the right direction!
> Add Debian build bug to readme

- CHANGELOG.md
- src/main.rs
- tests/smoke.rs
by telling rustdoc about the sysroot via RUSTDOCFLAGS
closes #42
this *should* fix #42 but I can't test this until rust-lang/rust#36586 lands
cc @cbiffle
> fix xargo doc

- CHANGELOG.md
- src/main.rs
- src/sysroot.rs
"backport" of rust-lang/cargo#3157
> per target rustflags

- src/main.rs
* Add a constant that get the current version of the crate
* Override `--version` option to display the current version of the crate and the current version of cargo
> Add fix to display the current version of the crate

- README.md
Building with just …
```bash
OPENSSL_ROOT_DIR=/usr/local/opt/openssl/ cargo install xargo
```
… fails on my machine (macOS 10.12).
It takes this mouthful …
```bash
LDFLAGS="-L/usr/local/opt/openssl/lib" \
CPPFLAGS="-I/usr/local/opt/openssl/include" \
PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig" \
OPENSSL_ROOT_DIR=/usr/local/opt/openssl/ \
cargo install xargo
```
… to succeed.
> Added additional environment variables for building on OSX

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- ci/run-docker.sh
- src/dag.rs
- src/main.rs
- src/sysroot.rs
this makes Xargo robust against changes in the std facade as all the
crate names that were hardcoded in Xargo, e.g. `rustc_unicode`, have
been removed.
The downside is that this also worsens the user experience because when
Xargo fails to build one of std dependencies it will simply regurgitate
the error to stderr.
cc @brson with this change, I won't get mad if you change the std facade :smile:.
> try to build all std dependencies including std

- CHANGELOG.md
- src/sysroot.rs
the path to the Rust source code must be specified via the
XARGO_RUST_SRC env variable.
cc @oli-obk
> support the dev channel

- CHANGELOG.md
- src/main.rs
- src/rustc.rs
and give it precedence over the `rust-src` component
> accept XARGO_RUST_SRC on the nightly channel too

- .travis.yml
- src/cargo.rs
- src/sysroot.rs
- tests/smoke.rs
with this is now possible to build the `test` crate which doesn't
explicitly depend on `std`.
This Xargo.toml
``` toml
[dependencies.std]
features = ["panic_unwind"]
[dependencies.test]
stage = 1
```
Builds the sysroot in two stages. First, Xargo builds the `std`
facade, the stage 0, turns that into a partial sysroot and then builds
the `test` crate, the stage 1, against that partial sysroot. Finally,
the stage 0 artifacts and the stage 1 artifacts are then merged into the
sysroot that will be used to build the application.
The result is that you can use `xargo test` with this Xargo.toml.
---
cc @jackpot51
> allow "multi-stage" sysroot builds

- src/sysroot.rs
this is mainly to support [steed] and other `std` drop in replacements
For example, with this Xargo.toml
``` toml
[dependencies.collections]  # `steed`s dependencies
[dependencies.std]  # use `steed` as if it were the real `std`
git = "https://github.com/japaric/steed"
stage = 1
```
you can use `xargo build` to compile your program against `steed`.
[steed]: https://github.com/japaric/steed
cc japaric/steed#20
> allow inserting foreign crates into the sysroot

- ci/install.sh
- src/rustc.rs
- tests/smoke.rs
now you get:
```
$ xargo build
error: `rust-src` component not found. Run `rustup component add rust-src`.
note: run with `RUST_BACKTRACE=1` for a backtrace
```
closes #124
> improve error message when the `rust-src` component is missing

- README.md
Add some shell magic so that the given command for using xargo with plugins actually works with all targets.
> README: automatically detect host platform target

- README.md
I (think I) finally [understood](https://github.com/rust-lang/rust/issues/43637#issuecomment-320463578) why libstd behaves so strangely wrt. dependong on liballoc_jemalloc and libpanic_unwind. This extends the README to explain that.
> extend std caveats description

- src/sysroot.rs
- src/xargo.rs
It took me a little while to realize that xargo does add some flags on its own here. Having this output would have helped :)
> print RUSTFLAGS in verbose mode

- src/main.rs
- src/sysroot.rs
This ensures we are using the exact versions of the packages that were used to build the libstd of this Rust release.
Cc #162
> use Cargo.lock file from rust-src if present

- README.md
> Add section to show how to disable jemalloc

- src/sysroot.rs
Allows custom targets to use the copy of `lld` bundled with Rust.
cc https://github.com/rust-lang/rust/issues/48772
> Copy bin directory to host sysroot

- .travis.yml
- Cargo.lock
- Cargo.toml
- ci/install.sh
- ci/script.sh
- src/errors.rs
- src/main.rs
- src/sysroot.rs
- src/xargo.rs
- tests/smoke.rs
Fixes https://github.com/japaric/xargo/issues/227
> Fix for latest nightly: need to add a patch section

- Cargo.lock
- src/sysroot.rs
```
error: intermittent IO error while iterating directory `.../rust/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/bin`
caused by: IO error for operation on .../rust/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/bin: No such file or directory (os error 2)
caused by: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` for a backtrace
```
> Don't error on missing rustlib/$TRIPLE/bin

- .travis.yml
However, I am not entirely happy with this yes: (a) it builds all jobs, maybe we want to exclude some, and (b) won't this also run Travis on master after bors pushes staging to master? That seems silly.
> have CI in branches

- .travis.yml
- Cargo.lock
- Cargo.toml
- ci/install.sh
- ci/script.sh
This bumps lazy_static to its 1.0.0. I also did a `cargo update`.
And I realized that in PRs we are not actually running any tests currently; this fixes our CI configuration for Traivs. (An AppVeyor config exists but AppVeyor does not even seem to be configured for this repo?)
r? @jethrogb
> Fix deprecation warning with latest nightly

- src/cargo.rs
- src/sysroot.rs
- src/xargo.rs
This is needed in https://github.com/rust-lang/rust/pull/63162 to make xargo work during rustc bootstrap.
r? @jethrogb
> let environment overwrite cargo command

- .travis.yml
- src/sysroot.rs
- tests/smoke.rs
Fixes xargo for https://github.com/rust-lang/rust/pull/63637
> fix for latest rustc

- README.md
This is very much a nit. Feel free to close and discard this PR if you wish.
It may also be worth getting rid of this line entirely. It appears that since 0.3.12 there have
only been Windows binary releases (excluding one linux one in 0.3.13).
> clarify operating systems with available binaries

- .travis.yml
- src/sysroot.rs
- tests/smoke.rs
This reverts a [prior revert](https://github.com/japaric/xargo/pull/190).
compiler-builtins is nowadays pulled in via crates.io, so let's give locking another shot.
> Use the lockfile shipped with rust-src

- src/xargo.rs
- tests/smoke.rs
So far, xargo expected the Xargo.toml in the directory of the Cargo.toml. This patch searches for the Xargo.toml by walking up the directory hierarchy. This is useful if a workspace is used, leading, for example, to one Cargo.toml with the workspace and multiple Cargo.toml files for the members of the workspace. With this patch, it is no longer necessary to have one Xargo.toml for each Cargo.toml, but only one next to the workspace, for example.
>  Search for Xargo.toml in parent directories, including test

- src/cli.rs
- src/main.rs
- src/sysroot.rs
Currently, `--message-format` is forwarded to the cargo building the final crate, but not when building the sysroot. This can break some tools that work by analyzing the output of `cargo build --message-format=json` when using xargo as a cargo replacement. (Split off from #217 )
> Pass message-format to the cargo building the sysroot

- CHANGELOG.md
- Cargo.toml
Right now Miri is broken on macOS and Windows because an updated compiler_builtins has problems, and we don't use the lockfile that would make us use the old version.
So, it's time to release a xargo with https://github.com/japaric/xargo/pull/255.
> version bump for 0.3.17 release

- src/sysroot.rs
If the sysroot and project share a dependency, it might cause conflicts, leading to confusing cargo errors. See https://github.com/roblabla/xargo-reproducer for a reproducer of the issue. This is the same patch as #217 .
Fixes #261 
I have a way to reproduce the issue this time around (see the issue), but I'm having a hard time figuring out how to properly integrate it within xargo's smoketest. I don't think it's really possible to do in a robust way, actually...
> Force different metadata for sysroot crates

- README.md
Compiler builtins is automatically built and linked as part of libcore - it is generally unnecessary to specify it in the Xargo.toml.
Adds a section detailing the (most common) cause of multiple matching crates error.
Replaces steed with rust-3ds as an example custom std facade, as it is an up-to-date, working example of a custom std facade.
> Fix custom std example in README

- src/sysroot.rs
- tests/smoke.rs
Unfortunately we cannot test `--target x86_64-pc-windows-gnu` until https://github.com/rust-lang/backtrace-rs/pull/297 lands and propagates. But I confirmed locally that using both together makes that target work on my Linux box.
> skip copy of windows-gnu libs in check-only mode

- src/lib.rs
This will likely just lead to failures later, so we better don't continue.
> make xargo fail on non-nightly, instead of continuing with the wrong sysroot

- src/rustc.rs
- src/sysroot.rs
- src/xargo.rs
This should help with issues such as [this one](https://github.com/rust-lang/rust/pull/74146#issuecomment-655723028).
> avoid adding '/' or '..' to paths for better Windows compatibility

- src/rustc.rs
We need to canonicalize the path because we change working directory before using it.
> support relative XARGO_RUST_SRC

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
r? @jethrogb 
Would be good to get this out ASAP, it blocks https://github.com/rust-lang/miri/pull/1490.
> release xargo 0.3.22

- .github/workflows/ci.yml
Fix bors-ng/bors-ng#1129
Sorry about breaking your workflow.
> Get rid of now-unnecessary ci-failure job

- src/sysroot.rs
Fixes #286 
According to @RalfJung (https://github.com/japaric/xargo/issues/286#issuecomment-607675112). It's better to use default `target`. So we just need to explicit override the target directory to fix the copy failure.
> xargo has its own workspace for building libstd. There is no interaction whatsoever with the workspace of your project. That's why I keep saying xargo should just overwrite the target dir.
> Fix copy failure by overriding CARGO_TARGET_DIR

- .github/workflows/ci.yml
- Cargo.toml
- src/sysroot.rs
- tests/smoke.rs
I am not entirely sure why this was added, but not having `cargo test` run the main test suite has been eternally confusing... I think we better just get rid of this feature.
> remove 'dev' feature

- src/sysroot.rs
Fixes #320, but I am not sure, what the previous behavior was!
> reference compiler-builtins by git source

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
We should get the fix to https://github.com/japaric/xargo/issues/320 shipped.
@jethrogb any objections?
> release xargo 0.3.24

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
A significant fraction of the time for building xargo is spent on `backtrace` and its dependencies. In normal operation, backtraces shouldn't even come up, so I propose we disable this feature by default. Backtraces remain available as an optional feature (which can help with debugging).
(I care about xargo build times because `cargo miri setup` on CI is bottlenecked on building xargo.)
Also update dependencies while I am at it.
> disable backtraces by default

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Let's get https://github.com/japaric/xargo/pull/336 out there.
> release xargo 0.3.26
